format = """
[ïŒƒ ](#02d1fa)\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$conda\
$character"""

# Make prompt a single line instead of two lines
# [line_break]
# disabled = true


[username]
show_always = true
style_user = "#d861ed bold"
style_root = "#F60909 bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
disabled = false
format = "[@$hostname](#d861ed bold) "

[directory]
style = "#5f94e3"
truncation_symbol = ".../"
read_only = " ï ½"


[character]
success_symbol = "[â¯](#2dc24f)"
error_symbol = "[â¯](#c22d2d)"
vimcmd_symbol = "[â®](#bac22d)"


[git_branch]
symbol = 'î‚  '
style = "#f56f42"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#f56f42"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
# format = "[$virtualenv]($style) "
# style = "bright-black"
symbol = "îˆµ "

[conda]
symbol = "ğŸ "  # El sÃ­mbolo distintivo que aparecerÃ¡ cuando el entorno de conda estÃ© activo.
style = "bold green"  # Personaliza el color y estilo.
